from run import db,Publication,Book
pub=Publication(100,'Oxford Publication')
db.session.add(pub)
db.session.commit()
paramount=Publication(102,'Paramount Press')
oracle=Publication('103','Oracle INC.')
db.session.add_all([paramount,oracle])
db.session.commit()

#change after removing the previous data
p1=Publication("Oxford Publication")
p2=Publication("Paramount Press")
p3=Publication("Oracle Books Inc")
p4=Publication("Vintage Books and Comics")
p5=Publication("Trolls Press")
p6=Publication("Broadway Press")
p7=Publication("Downhill Publishers")
p8=Publication("kingfisher Inc")
db.session.add_all([p1,p2,p3,p4,p5,p6,p7,p8])

b1=Book("Milk's delivery Service","William Dobelli",3.9,"ePub","broom-145379.svg",123,1)
b2=Book("The Secret Life of Walter Kitty","Kitty Stiller",4.1,"Hardcover","cat-150306.svg",133,1)
b3=Book("The Empty Book of Life","Roy Williamson",4.2,"eBook","book-life-34063.svg",153,1)
b4=Book("Life After Death","Nikita Kimmel",3.8,"Paperback","mummy-146868.svg",175,2)
b5=Book("Sali The Dali","Charles Rowling",4.6,"Handcover","el-salvador-dail-889515.jpg",253,2)
b6=Book("Taming Dragons","James Vonnegut",4.5,"MassMarket Paperback","dragon-23165.svg",229,2)
b7=Book("The Singing Magpie","Oscar Steinbeck",5,"Handcover","magpie-147852.svg",188,3)
b8=Book("Mr.Incognito","Amelia Funke",4.2,"Hardcover","incognito-160243.svg",205,3)
b9=Book("A Dog without purpose","Edgar Dahl",4.8,"MassMarket Paperback","dog-159271.svg",300,4)
b10=Book("A Frog's Life","Herman Capote",3.9,"Massmarket Paperback","ambhibian-150342.svg",190,4)
b11=Book("Logan Returns","Margaret Elliot",4.6,"Handcover","wolf-153648.svg",279,5)
b12=Book("Thieves of Kaalapani",'Mohit Gustav',4.1,"Paperback","boat-1296201.svg",270,5)
b13=Book("As Men Thinketh","Edward McPee",4.5,"Paperback","cranium-2028555.svg",124,6)
b14=Book("Mathematics of Music","Mary Turing",4.5,"Handcover",'music-306008.svg',120,6)
b15=Book("The Mystery of Mandalas","Jack Morrison",4.2,"Paperback","mandala-1817599.svg",221,6)
b16=Book("The Sacred Book of Kairo","Heidi Zimmerman",3.8,"ePub","book-1294676.svg",134,7)
b17=Book("Love is Forever,As Long as it lasts","Kovi O'Hara",4.5,"Hardcover","love-2026554.svg",279,8)
b18=Book("Order in Chaos","Wendy Sherman",3.5,"MassMarket Paperback","chaos-1769656.svg",140,8)
db.session.add_all([b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,b11,b12,b13,b14,b15,b16,b17,b18])
db.session.commit()


all=Book.query.all()
print(all)
print(all[:3])
first=Book.query.first()
print(first)
filter_data=Book.query.filter_by(format='ePub').all()
print(filter_data)
pk=Book.query.get(1)
print(pk)
k=Book.query.limit(5).all()
print(k)
order_records=Book.query.order_by(Book.title).all()
print(order_records)
fo=Book.query.filter_by(format="Paperback").order_by(Book.title).all()
print(fo)

#query two tables
result=Publication.query.filter_by(name="Broadway Press").first()
print(result.name)
print(result.id)
broadway=Book.query.filter_by(pub_id=result.id).all()
print(broadway)


#update and delete table
u=Book.query.get(16)
print(u.id)
print(u.title)
print(u.format)
u.format="Hardcover"
db.session.commit()
#delete
x=Book.query.get(10)
db.session.delete(x)
db.session.commit()
db.session.close()
#when multiple queries are there and it is hard to delete ,then use it
#first delete from child table then,parent table
Book.query.filter_by(pub_id=6).delete()
db.session.commit()
Publication.query.filter_by(id=6).delete()
db.session.commit()
